stages:
  - build
  - analysis
  - testing
  - reporting

build:composer:
  stage: build
  image: php:7.0
  before_script:
    # Install git&ssh
    - apt-get update -yqq
    - apt-get install openssh-client -yqq > /dev/null
    - apt-get install git -yqq > /dev/null

    # Setup ssh
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa git.prod.sup.fdmg.org,$(dig +short git.prod.sup.fdmg.org) >> ~/.ssh/known_hosts
    - '[[ -f /.dockerinit ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

    - apt-get install -yqq libc-client-dev libkrb5-dev > /dev/null
    - docker-php-ext-install zip > /dev/null
    - curl --silent --show-error https://getcomposer.org/installer | php
  script:
    - php composer.phar install --no-suggest --no-interaction --ignore-platform-reqs --no-progress
  cache:
    paths:
      - vendor
      - .composer/cache
  artifacts:
    paths:
      - vendor

analysis:sonarqube-feedback:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: "https://sonar.fdmg.org"
    SONAR_PROJECT_VERSION: "$CI_BUILD_ID"
    SONAR_ANALYSIS_MODE: "issues"
  script:
    - /usr/bin/sonar-scanner-run.sh

reporting:sonarqube-report:
  stage: reporting
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: "https://sonar.fdmg.org"
    SONAR_PROJECT_VERSION: "$CI_BUILD_ID"
    SONAR_ANALYSIS_MODE: "publish"
  script:
    - unset CI_BUILD_REF && /usr/bin/sonar-scanner-run.sh
  dependencies:
    - testing:phpunit

analysis:php-cs-fixer:
  stage: analysis
  image: php:7.0-alpine
  script:
    - vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --allow-risky=yes --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB HEAD~..$CI_BUILD_REF`
  dependencies:
    - build:composer

analysis:security-checker:
  stage: analysis
  image: php:7.0-alpine
  script:
    - vendor/bin/security-checker security:check composer.lock
  dependencies:
    - build:composer

testing:phpunit:
  stage: testing
  image: alpine:3.5
  before_script:
    - wget -O /etc/apk/keys/php-alpine.rsa.pub http://php.codecasts.rocks/php-alpine.rsa.pub
    - echo "http://php.codecasts.rocks/7.0" >> /etc/apk/repositories
    - apk add --update sudo sqlite
    - >
      apk add --update
      php7
      php7-bcmath
      php7-dom
      php7-iconv
      php7-ctype
      php7-json
      php7-soap
      php7-xml
    - sudo ln -s /usr/bin/php7 /usr/bin/php
  script:
    - php vendor/bin/phpunit --coverage-text --colors=never --exclude-group functional
  dependencies:
    - build:composer
  artifacts:
    paths:
      - report/phpunit
